Sprint1/step2
gasandm/react-burger pull request #2
Opened 2021-06-30 20:32 UTC by gasandm

моlалки можно посмотреть раскомментировав компоненты в components/app/app.js

2021-07-15 19:06 UTC, AygulMalikova requested changes
Отличная работа! У вас хорошо структурированный и чистый код, разделенный на компоненты.

Но есть небольшие замечания, которые указаны в комментариях в пул-реквесте. А именно

- модальные окна не закрываются с помощью ESC и нажатием на оверлей
- реализация портала
- использование селекторов по тегам, повторяющиеся свойства, стиль написания классов

И также, были оставлены другие комментарии и рекомендации по улучшению вашего кода.

Я напоминаю, что работа будет принята, как только все критические ошибки будут исправлены. Желаю вам удачи!

2021-07-15 19:06 UTC, AygulMalikova commented on src/components/app/app.js
> +import OrderAccepted from "../order-accepted/order-accepted";
 Можно лучше:
 
OrderAccepted и IngredientDetails не используются в данном файле. Следует удалить неиспользуемые импорты

2021-07-15 19:06 UTC, AygulMalikova commented on src/components/app/app.js
> +    const[data, setData] = React.useState([]);
Надо исправить:

Очень важно иметь правильно отформатированный код для улучшения его читабельности. Пожалуйста, обратитесь к данной статье для изучения стандартов https://learn.javascript.ru/coding-style

Если вы используете IDE (например, VS code), то вы можете автоматически форматировать ваш код:
 https://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode

2021-07-15 19:06 UTC, AygulMalikova commented on src/components/app/app.js
> +        fetch(API)
Можно лучше:

Несмотря на то, что некоторые свойства второго аргумента options у метода fetch установлены по дефолту, рекомендуется все же прописывать их явно. Например: 
```
{
  method: 'GET',
  headers: {
    "Content-Type": "application/json",
  }
}
```

2021-07-15 19:06 UTC, AygulMalikova commented on src/components/app/app.module.scss
> +    margin-top: 40px;
Надо исправить:

Вы можете объединить это свойство и свойство выше в одно

2021-07-15 19:06 UTC, AygulMalikova commented on src/components/app-header/app-header.module.scss
> +header {
Надо исправить:

Не рекомендуется использовать селекторы по тегу. Вам следует дать элементам (уникальные) классы

2021-07-15 19:06 UTC, AygulMalikova commented on src/components/app-header/app-header.module.scss
> +.navElement {
Надо исправить:

Сейчас у вас в наименовании классов используются разные подходы: camelCase и kebab-case. Вам следует выбрать один из них и придерживаться во всем проекте. Я рекомендую вам для наименования классов использовать kebab-case

2021-07-15 19:06 UTC, AygulMalikova commented on src/components/burger-constructor/burger-constructor.module.scss
> +            display: flex;
Надо исправить:

В данном селекторе свойство display указано дважды

2021-07-15 19:06 UTC, AygulMalikova commented on src/components/burger-ingredients/burger-ingredients.js
> +BurgerIngredients.propTypes = { data: PropTypes.arrayOf(PropTypes.object) };
Для ингредиента вам следует создать отдельный тип, прописав все его поля, чтобы использовать его для определения типа вместо PropTypes.object

2021-07-15 19:06 UTC, AygulMalikova commented on src/components/ingredient/ingredient.js
> +        <div key={_id} onClick={() => props.toggleDetails(props.item)} className={styles.ingridient}>
Можно лучше:

ingridient -> ingredient

2021-07-15 19:06 UTC, AygulMalikova commented on src/components/modal/modal.js
> +            <div className={`${styles.details} text text_type_main-large mt-40 ml-40`}>
Надо исправить:

Стили для класса details определены в modal.module.css, а не в ingredient-details.module.scss

2021-07-15 19:06 UTC, AygulMalikova commented on src/components/modal/modal.js
> +
Надо исправить:

На данный момент модальные окна не закрываются нажатием на оверлей или с помощью ESC. Пожалуйста, добавьте необходимый функционал.

Также обратите внимание, что портал должен быть использован для самого модального окна (т.е. внутри компонента Modal), а не внутри компонентов IngredientDetails и OrderAccepted. ModalOverlay - это фон для окна. 

Пожалуйста, обратитесь к данному уроку, чтобы вспомнить как необходимо реализовать модальные окна с помощью портала: https://practicum.yandex.ru/learn/react/courses/b512c4ac-8797-4b96-935a-6b2865f27c9a/sprints/6021/topics/3daef531-37a0-4521-ac9c-dac879418335/lessons/f60fe57f-6c77-446c-966d-1fefe0413a9f/

2021-07-15 19:06 UTC, AygulMalikova commented on src/components/app-header/app-header.js
> +const AppHeader = () => {
Отлично, что вы используете функциональные компоненты!

2021-07-18 11:50 UTC, AygulMalikova commented
Отличная работа! Вы исправили немало ошибок, и вы движетесь в правильном направлении!
Осталось исправить одну ошибку и ваша работа будет принята. На данный момент при открытии модального окна появляется горизонтальная прокрутка (https://prnt.sc/1cmnjxj). Пожалуйста, исправьте, чтобы ее не было.

Удачи!

2021-07-18 19:54 UTC, AygulMalikova commented
Хорошо! На данный момент при прокручивании страницы вниз при открытом модальном окне затемненный фон заканчивается: https://prnt.sc/1crwp5k. Вам следует зафиксировать модальное окно, чтобы фон не пропадал при прокрутке. Более того прошу обратить внимание, что горизонтальная прокрутка при открытии модального все еще присутствует на разных разрешениях, например, 1024 на 768 (https://prnt.sc/1crvhvr). 

Можно лучше: также желательно исправить, чтобы горизонтальной прокрутки страницы (не только при открытом попапе) вовсе не было. 

Вам осталось исправить совсем немного, желаю вам успехов!

2021-07-18 20:07 UTC, gasandm commented
> Хорошо! На данный момент при прокручивании страницы вниз при открытом модальном окне затемненный фон заканчивается: https://prnt.sc/1crwp5k. Вам следует зафиксировать модальное окно, чтобы фон не пропадал при прокрутке. Более того прошу обратить внимание, что горизонтальная прокрутка при открытии модального все еще присутствует на разных разрешениях, например, 1024 на 768 (https://prnt.sc/1crvhvr).
> 
> Можно лучше: также желательно исправить, чтобы горизонтальной прокрутки страницы (не только при открытом попапе) вовсе не было.
> 
> Вам осталось исправить совсем немного, желаю вам успехов!

Адаптив сделаю ближе к концу курса. Пока не хотелось бы на это тратить время. Ваш сервис хранения скриншотов не работает:)

2021-07-18 20:12 UTC, AygulMalikova commented
Будет здорово, если вы добавите к вашему проекту адаптив :)
На данный момент ваша работа принята, я вас поздравляю! Все ошибки исправлены и все условия задания выполнены. У вас отличный код, поделенный на компоненты. Так держать! Еще раз поздравляю и желаю вам дальнейших успехов!

2021-07-18 21:34 UTC, merged