Sprint2/step2
gasandm/react-burger pull request #4
Opened 2021-08-03 21:55 UTC by gasandm

2021-08-04 19:57 UTC, AygulMalikova requested changes
Отличная работа! 

У вас хорошо структурированный и чистый код, разделенный на компоненты, весь необходимый функционал реализован!

Но есть небольшие замечания:

- контекст следует удалить, т.к. сейчас используется Redux
- исправьте, чтобы при закрытии модального окна ингредиента с помощью ESC не было ошибок
- при завершении запроса необходимо проверить, что он завершился успешно

И также, были оставлены другие комментарии и рекомендации по улучшению вашего кода.

Я напоминаю, что работа будет принята, как только все критические ошибки будут исправлены. Желаю вам удачи!

2021-08-04 19:57 UTC, AygulMalikova commented on src/components/app/app.js
> +                    <IngredientsContext.Provider value={data}>
**Надо исправить:**
Сейчас вы используете Redux, поэтому в контексте больше нет необходимости. Его следует удалить

2021-08-04 19:57 UTC, AygulMalikova commented on src/components/burger-ingredients/burger-ingredients.js
> +    function toggleDetails(item) {
**Надо исправить:**

При закрытии модального окна с помощью ESC на странице появляется ошибка: TypeError: Cannot read property '_id' of undefined

2021-08-04 19:57 UTC, AygulMalikova commented on src/services/reducers/ingredientsSlice.js
> +        .then((res) => res.json())
Надо исправить:

При завершении запроса необходимо проверить, что он завершился успешно - `res.ok`
[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)[https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch#Проверка_успешности_запроса](https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch#%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0_%D1%83%D1%81%D0%BF%D0%B5%D1%88%D0%BD%D0%BE%D1%81%D1%82%D0%B8_%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0)

```
if (!res.ok) {
    return Promise.reject(`Ошибка: ${res.status}`); 
}
return res.json();
```

Пожалуйста, исправьте это также в других запросах

2021-08-04 19:57 UTC, AygulMalikova commented on src/components/burger-constructor/burger-constructor.js
> +    var bun = addedIngredients.find((item) => item.type === "bun");
**Надо исправить:**
Для объявления переменной необходимо использовать `let`, либо `const`.

Если переменная объявлена ​​с помощью `let`, ее значение следует переписать напрямую в коде. Если значение переменной никогда не перезаписывается напрямую, оно должно быть объявлено с помощью `const`. Это помогает другим разработчикам понять назначение переменной. Имейте в виду, что добавление элемента в массив или обновление свойства объекта - это не то же самое, что перезапись самой переменной. Если изменяется только внутреннее состояние переменных, объявите их с помощью `const`.

2021-08-04 19:57 UTC, AygulMalikova commented on src/components/burger-constructor/burger-constructor.js
> +        bun = {
Можно лучше:
Данный объект следует вынести в отдельную переменную и разместить в отдельном файле

2021-08-04 19:57 UTC, AygulMalikova commented on src/components/burger-constructor/burger-constructor.js
> +                        text={bun.name + " (верх)"}
**Можно лучше:**

Здесь и в других местах вы можете воспользоваться шаблонными строками https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals

2021-08-04 19:57 UTC, AygulMalikova commented on src/components/burger-ingredients/burger-ingredients.module.scss
> +        div {
Надо исправить:

Использовать селекторы по тегу - не самый лучший подход. Вам следует дать элементам уникальные классы. Пожалуйста, исправьте это здесь и в других местах

2021-08-04 19:57 UTC, AygulMalikova commented on src/components/ingredient-in-constructor/ingredient-in-constructor.js
> +    item: PropTypes.object.isRequired,
Можно лучше:

Вместо object вам следует использовать тип с расписанными полями объекта

2021-08-06 21:00 UTC, gasandm commented
Селекторы по тегу использую т.к. не имею прямого доступа к элементу

2021-08-07 07:08 UTC, AygulMalikova commented
Ваша работа принята, я вас поздравляю! Все ошибки исправлены и все условия задания выполнены. У вас отличный код, поделенный на компоненты. Так держать!
Буду рада вашей обратной связи. Еще раз поздравляю и желаю вам дальнейших успехов!

2021-08-08 12:26 UTC, merged